### PR TITLE
Add detail about saving payloads to install-venv

### PR DESCRIPTION
**Pull request by danmarsden**

### CODE REVIEW

**Comment by douglasbagnall** [comment]
Looks accurate and useful.

**Comment by danmarsden** [comment]
@ilyatregubov this is just a change to the docs to describe an extra option for debugging  - no code changes here. :-)

**Comment by danmarsden** [comment]
it's probably worth mentioning we could tidy up the readme in the project to link to this file - I would expect that most  people coming to github are likely to want to build this using something similar to the steps documented in install-venv rather than the steps for generating a python package and uploading it to the package index which is likely something only HQ staff will do.

**Comment by douglasbagnall** [comment]
Also worth noting is there are changes in our production branch:
https://github.com/catalyst/moodle-mlbackend-python/blob/catalyst-3.4/INSTALL-venv.md
(commit 7a707427c0217e64a339528d8fe0feee149b91bc).

I haven't worked out which changes can be backported here, but I suspect most should be. 
This document is currently more indicative than accurate.

**Comment by ilyatregubov** [comment]
Aha. Just some more extra debugging info. Ok will merge soon. No need of new version for this one.

**Pull request merged**
